sweetshop/desserts/urls.py
from django.urls import path

from .views import *

app_name = 'list'

urlpatterns = [
    path('', Index.as_view(), name='index'), # виды десертов с подписями и фотографиями
    path('examples/<int:id>/', examples, name='example'),
    path('filling/', filling, name='filling'),
    path('filling_type/<int:id>/', filling_type, name='filling_type'),
    path('filling_detail/<int:id>/', filling_detail, name='filling_detail')
    # path('create/', CreateWish.as_view(), name='create'),
    # path('edit/<int:wish_pk>/', UpdateWish.as_view(), name='edit_wish'),
    # path('delete/<int:wish_pk>/', DeleteWish.as_view(), name='delete_wish'),
    # path('details/<int:pk>/', DetailWish.as_view(), name='details_wish')
]

sweetshop/feedback/urls.py
from django.urls import path

from .views import about, contact, reviews

app_name = 'feedback'

urlpatterns = [
    path('about/', about, name='about'), # виды десертов с подписями и фотографиями
    path('contact/', contact, name='contact'),
    path('reviews/', reviews, name='reviews'),
    
    # path('wish_user/<int:author_id>/', WishesForUser.as_view(), name='all_wish'),
    # path('about/', about, name='about'),
    # path('create/', CreateWish.as_view(), name='create'),
    # path('edit/<int:wish_pk>/', UpdateWish.as_view(), name='edit_wish'),
    # path('delete/<int:wish_pk>/', DeleteWish.as_view(), name='delete_wish'),
    # path('details/<int:pk>/', DetailWish.as_view(), name='details_wish')
]

sweetshop/sweetshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('desserts.urls', 'desserts')),
    path('feedback/', include('feedback.urls', 'feedback')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

sweetshop/templates/includes/filling_sidenav.html
{% load my_custom_tags %}

{% get_all_example_filling as examples %}

<div class="sidenav">
    <ul class="sidenav_list">
       {% for obj in examples %}
     <li><a href="{% url 'desserts:filling_type' id=obj.id %}">{{ obj.title }}</li></a>   
       {% endfor %}
   </ul>
   </div>

sweetshop/templates/includes/header.html
<div class="header_text" text-align="right">Missis Vanilka</div>
{% block mainmenu %}
<div>
  <ul class="mainmenu">
            <li><a href="{% url 'desserts:index' %}">Примеры работ</a></li>
            <li><a href="{% url 'desserts:filling' %}">Начинки</a></li>
            <li><a href="#">Конструктор торта</a></li>
            <li><a href="#">Заказ по фото</a></li>
            <li><a href="{% url 'feedback:reviews' %}">Отзывы</a></li>
            <li><a href="{% url 'feedback:about' %}">Обо мне</a></li>
            <li><a href="{% url 'feedback:contact' %}">Контакты</a></li>
  </ul>
</div>
{% endblock mainmenu %}

sweetshop/templates/includes/open_image.html
<script>

    document.querySelectorAll('.card_img img').forEach(img =>{
        img.onclick = () => {
            document.querySelector('.pop-up').style.display = 'block';
            document.querySelector('.pop-up img').src = img.getAttribute('src');
        }
    });

    document.querySelector('.pop-up span').onclick = () => {
        document.querySelector('.pop-up').style.display = 'none';
    }

</script>